const actionTypes = {
   FETCH_HASTALAR_START: "FETCH_HASTALAR_START",
   FETCH_HASTALAR_SUCCESS: "FETCH_HASTALAR_SUCCESS",
   FETCH_HASTALAR_FAIL: "FETCH_HASTALAR_FAIL",
   ADD_HASTA: "ADD_HASTA",
   DELETE_HASTA: "DELETE_HASTA",
   EDIT_HASTA: "EDIT_HASTA",
   FETCH_RANDEVULAR_START: "FETCH_RANDEVULAR_START",
   FETCH_RANDEVULAR_SUCCESS: "FETCH_RANDEVULAR_SUCCESS",
   FETCH_RANDEVULAR_FAIL: "FAIL_RANDEVULAR_FAIL",
   ADD_RANDEVU: "ADD_RANDEVU",
   DELETE_RANDEVU: "DELETE_RANDEVU",
   EDIT_RANDEVU: "EDIT_RANDEVU",
   FETCH_ISLEMLER_START: "FETCH_ISLEMLER_START",
   FETCH_ISLEMLER_SUCCESS: "FETCH_ISLEMLER_SUCCESS",
   FETCH_ISLEMLER_FAIL: "FAIL_ISLEMLER_FAIL",
   ADD_ISLEM: "ADD_ISLEM",
   DELETE_ISLEM: "DELETE_ISLEM",
   EDIT_ISLEM: "EDIT_ISLEM",
};

export default actionTypes;
